### ISSUE TITLE
Error messsage about missing email in new ticket view is duplicated

### ISSUE THREAD

**Issue by rschaerer** [scott/helpy#70] opened 2016-03-03 13:48 UTC
Maybe already fixed with #54 but I'm not sure about, because this happens on a different view than #54 is concerning:

If a non logged in user tries to create e new ticket on `/de/topics/new` and leaves the email fiel blank, the error message below the email input field is printed **tiwce** instead of **once**.

See this two picture of a german instance:
![selection_004](https://cloud.githubusercontent.com/assets/1032762/13496011/363c3c3a-e14e-11e5-9d22-9b11f6ab9a38.jpg)

**Comment by rschaerer** [comment] 2016-03-03 13:50
ah, i see that the sign up thing is a duplicate of #54. Did #54 also solve the same thing on the new ticket form?

**Comment by scott** [comment] 2016-03-03 15:06
Thanks for this, it looks like it would be pretty easy to fix.

**Comment by olliebennett** [comment] 2016-03-05 22:08
Hey, yeah the solution to #54 will almost certainly have fixed this too; that fix wasn't view-specific, but related to the model itself. Appreciate you raising it regardless; no objection to keeping this open until you verify it's resolved after the next release.

**Comment by scott** [comment] 2016-03-07 18:58
@rschaerer @olliebennett I just confirmed that this is resolved on master, so closing the issue-

![screen shot 2016-03-07 at 11 56 56 am](https://cloud.githubusercontent.com/assets/14369/13579635/cc94906e-e45b-11e5-9baa-d83a333e77f0.png)

**Closed by scott** 2016-03-07 18:58 UTC
Labels: bug
